version: '3.8'

services:
  learning-platform:
    build: .
    container_name: learning-platform-web
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.learning-platform.rule=Host(`localhost`)"
      - "traefik.http.services.learning-platform.loadbalancer.server.port=80"
    networks:
      - learning-network

  # Future services can be added here (e.g., database, API, etc.)
  # database:
  #   image: postgres:13-alpine
  #   container_name: learning-platform-db
  #   environment:
  #     POSTGRES_DB: learning_platform
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - learning-network

networks:
  learning-network:
    driver: bridge
    name: learning-platform-network

# volumes:
#   postgres_data:
#     name: learning-platform-postgres-data 